### ISSUE TITLE
Custom reservoirs

### ISSUE THREAD

**Issue by cyberfag** [blindedjoy/RcTorch#1]
Can one perform EchoStateNetworkCV using custom reservoir (adjacency) matrix, i.e.,  optimizing everything without randomly assigning reservoir matrix at each step (if it takes place at all)? I tried to add some parameters in the source code to make it possible (I manually assigned reservoir_matrices.reservoir_pre_weights in EchoStateNetworkCV and protected it from changing, then, after optimization, passed it to 'reservoir' parameter in EchoStateNetwork), it seems to have worked, but I'm not sure if the matrix is kept intact throughout the whole procedure since I cannot yet comprehend the whole code.

**Comment by blindedjoy** [comment]
hello @cyberfag the software has been dramatically upgraded, simplified and the variable names have been changed. If you would still like to create custom reservoirs please reach out to me at hnjoy@mac.com and I will be happy to work with you to accomplish your research goals.
